version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules # Evita que node_modules local sobreescriba el del contenedor
    depends_on:
      - db
    env_file:
      - ./apps/backend/.env
    environment:
      - DATABASE_URL=postgresql://wolfi:supersecret@db:5432/wolfidb
    command: npm run start:dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    command: npm run dev

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=wolfi
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=wolfidb

volumes:
  postgres_data:
